# Generated by Django 5.1.4 on 2025-01-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thambnail',
            field=models.ImageField(blank=True, null=True, upload_to='post_thumbnails'),
        ),
    ]
